_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: de26de6d-391a-4ecb-8bc8-ab7cf5b0f4f6
name: 'Drupal dev'
mail: noreply@drupal-dev.info
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
